### ISSUE TITLE
Route filter with label and mixin loses the label filter part

### ISSUE THREAD

**Issue by pangloss** [pangloss/pacer#33]
graph.e(label, Mixin) turns into graph.e(Mixin).

Workaround: graph.e(label).e(Mixin)...

**Comment by joeyfreund** [comment]
The behaviour is a little strange ...

```ruby
g.e(label)              # OK
g.e(Mixin)             # Route conditions are ignored
g.e(label, Mixin)   # Route conditions are ignored

g.v.out_e(label)     # OK
g.v.out_e(Mixin)    # OK
g.v.out_e(label, Mixin)    # Filtering is correct, but each element is returned twice
```

Now, this is where the behaviour gets a little odd.
If we pass _the same label_ more than once, we get duplicate results ...
```ruby
g.v.out_e(label, label)    # Each item is included twice in the result
g.v.out_e(label, label, label)    # Each item is included three times in the result

# But, when we apply the filters on the graph route ...
g.e(label, label, label)    # OK, each item is included once in the result
```

So, basically, it seems like edge filtering works differently on a graph route than on a vertex route.

**Comment by joeyfreund** [comment]
Seems like the bug is specific to TinkerGraph.

**Comment by pangloss** [comment]
Only the problem where an edge can be returned multiple times if duplicate labels are specified is TinkerGraph specific. The problem with as originally reported is in Pacer.

**Comment by joeyfreund** [comment]
Actually ... it seems like the duplicate items in result is not TinkerGraph specific.

I am using Neo4j for the following examples.

This one is OK ...
```ruby
jruby-1.7.18 :045 > g.e(:flies_to).count
 => 6 
jruby-1.7.18 :046 > g.e(:flies_to, :flies_to).count
 => 6
```

But then, when I get the edges by traversing out of a vertex ...
```ruby
jruby-1.7.18 :048 > g.v.out_e(:flies_to).count
 => 6 
jruby-1.7.18 :049 > g.v.out_e(:flies_to, :flies_to).count
 => 12 
```

As expected, the same happens with in edges
```ruby
jruby-1.7.18 :050 > g.v.in_e(:flies_to).count
 => 6 
jruby-1.7.18 :051 > g.v.in_e(:flies_to, :flies_to).count
 => 12
jruby-1.7.18 :052 > g.v.in_e(:flies_to, :flies_to, :flies_to).count
 => 18
```

**Comment by joeyfreund** [comment]
Seems like there are a number of issues here.

#### Logic issue

Say that `Mixin` is an extension with route_conditions that matches the label `label2`.     
The query `e(label1,Mixin)` will return edges whose label is `label1` **or** `label2`, and wrap each edge in `Mixin`.     
That is, `label1` edges will be included in the result, and will be wrapped in `Mixin`, although they violate `Mixin`'s route conditions.

#### Starting from a Graph vs. a Vertex Route

 * `g.e(Mixin)` is not working properly - It returns all the edges in the graph and ignores the route conditions.      
 * `g.e(label,Mixin)` behaves exactly the same as `g.e(Mixin)`.
 * `g.v.out_e(Mixin)` works fine (i.e. only edges that satisfy the route conditions are included in the result).
 * `g.v.out_e(label,Mixin)`
   * If the route condition of `Mixin` is to match a label other than `label`, then we suffer from the logic issue mentioned above.
   * If the route condition of `Mixin` is to match the label `label`, then the result will include the correct set of edges, but each edge will be included twice (because the `Mixin` becomes another label-filter, based on its route conditions, and currently duplicate labels cause duplicate results).

----

In my opinion, the correct behaviour should be as followes:    
The query `.e(label1,label2,Mixin1,Mixin2)` should translate logically to
`(edges with label1 OR label2) AND (edges that satisfy the route conditions of Mixin1 AND Mixin2)`

**Comment by pangloss** [comment]
I agree. When mixins are used, their labels should be deduplicated. When labels are passed in as regular arguments to a filter, I'm not sure what we should do. I actually think this bug should be reported to Blueprints and maybe also to Neo4j. Orient behaves correctly in this case.

As for the case of `g.e(Mixin)`, that definitely needs to be fixed.
