### ISSUE TITLE
Building a pacer adapter for graph db's

### ISSUE THREAD

**Issue by rrphotosoft** [pangloss/pacer#73]
Hi,
I was wondering where to start if I wanted to build a pacer adapter for a graph database implementation based on Tinkerpop that is not currently supported with pacer?
I looked at the Titan-pacer gem and the neo4j-pacer gem, but I could'nt make much sense of what was going on. Could you point me in the right direction?
I need some kind of a map that I should follow, I have arango, accumulo and flux graph in mind.
Many Thanks,
Bhargav.

**Comment by pangloss** [comment]
Hi Bhargav,

That'd be great if you want to create those database adaptors!

Fundamentally, it's very easy to create an adaptor, but they begin to look more complex because the adaptors are also the place for graph-specific features to be supported. That's why for instance the Neo4j adaptor has cypher and lucene functions defined on a custom graph subclass. The other thing that is good to implement in a graph adaptor is a custom encoder that best matches Ruby's data types to the types supported by the graph.

The best example to work from is probably the pacer-orient adaptor, but really you only need to look at lib/pacer_orient.rb (except #orient_factory) and lib/pacer_orient/rspec.rb.

Start out by simply instantiating a plain PacerGraph in the open block of the graph constructor. The open and shutdown procs allow the graph to be restarted while using the same PacerGraph instance. A simplified example:

```ruby
    def my_graph(url = nil, args = nil)
        open = proc do
          com.mygraph.MyGraph.new(url, args)
        end
        shutdown = proc do |g|
          g.shutdown
        end
        Pacer::PacerGraph.new Pacer::YamlEncoder, open, shutdown
      end
    end
```

Later you could improve it by creating the custom encoder. Something like lib/pacer_orient/encoder.rb.

You can test a graph by cloning the pacer repo, pointing Pacer's Gemfile to the path of your graph plugin, and adding a couple of references to it in Pacer's test suite setup.

Good luck!

Darrick

**Comment by rrphotosoft** [comment]
Hi Darrick,
Thanks for the "init"!!
Let me dig into 'pacer-orient' a bit, and I'll get back with progress and/or questions.
Regards,
Bhargav.
